#!/usr/bin/env python3
"""Generates both halves of the script ABI from Source/Scripting/ScriptAPI.def.

  Source/Scripting/Generated/ScriptEngineAPI.generated.h      C++ struct ScriptEngineAPI
  Modules/ScriptCore/Source/Generated/EngineAPIBindings.g.cs   C# struct EngineAPIBindings

  Engine/Tools/GenerateScriptAPI.py           # write both files
  Engine/Tools/GenerateScriptAPI.py --check   # exit 1 if either is out of date
"""
import os
import re
import sys

ENGINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ENGINE, "Source/Scripting/ScriptAPI.def")
CPP_OUT = os.path.join(ENGINE, "Source/Scripting/Generated/ScriptEngineAPI.generated.h")
CS_OUT = os.path.join(ENGINE, "Modules/ScriptCore/Source/Generated/EngineAPIBindings.g.cs")

# manifest type -> (C++ type, C# type)
TYPES = {
    "void": ("void", "void"),
    "bool": ("bool", "byte"),
    "int": ("int", "int"),
    "float": ("float", "float"),
    "cstr": ("const uint8_t*", "byte*"),
    "Entity": ("EntityID", "Entity"),
    "Entity*": ("EntityID*", "Entity*"),
    "Vector2*": ("Vector2*", "Vector2*"),
    "Vector3*": ("Vector3*", "Vector3*"),
    "const Vector3*": ("const Vector3*", "Vector3*"),
    "float*": ("float*", "float*"),
    "int*": ("int*", "int*"),
    "bool*": ("uint8_t*", "byte*"),
    "byte*": ("uint8_t*", "byte*"),
    "RaycastHit*": ("ScriptRaycastHit*", "RaycastHit*"),
}

LINE = re.compile(r"^(?P<ret>[\w*]+)\s+(?P<name>\w+)\s*\((?P<args>.*)\)\s*$")


def parse():
    sections = []
    names = set()
    with open(MANIFEST, encoding="utf-8") as f:
        for number, raw in enumerate(f, 1):
            line = raw.strip()
            if not line or (line.startswith("#") and not line.startswith("##")):
                continue
            if line.startswith("##"):
                sections.append((line[2:].strip(), []))
                continue
            match = LINE.match(line)
            if not match:
                sys.exit(f"{MANIFEST}:{number}: can't parse '{line}'")
            ret, name, args = match["ret"], match["name"], match["args"].strip()
            if ret not in TYPES:
                sys.exit(f"{MANIFEST}:{number}: unknown return type '{ret}'")
            if name in names:
                sys.exit(f"{MANIFEST}:{number}: '{name}' is declared twice")
            names.add(name)
            params = []
            if args:
                for arg in args.split(","):
                    parts = arg.strip().rsplit(" ", 1)
                    if len(parts) != 2 or parts[0].strip() not in TYPES:
                        sys.exit(f"{MANIFEST}:{number}: bad parameter '{arg.strip()}'")
                    params.append((parts[0].strip(), parts[1]))
            if not sections:
                sections.append(("", []))
            sections[-1][1].append((ret, name, params))
    return sections


def cpp(sections):
    out = [
        "// Generated by Engine/Tools/GenerateScriptAPI.py from Source/Scripting/ScriptAPI.def - edit the manifest, not this file.",
        "#pragma once",
        "#include <cstdint>",
        "",
        '#include "ECS/EntityID.h"',
        '#include "Math/Vector2.h"',
        '#include "Math/Vector3.h"',
        "",
        "// A physics query result as scripts see it (matches ScriptCore's RaycastHit).",
        "struct ScriptRaycastHit",
        "{",
        "    EntityID Entity;",
        "    Vector3 Point;",
        "    Vector3 Normal;",
        "    float Distance = 0.f;",
        "};",
        "",
        "struct ScriptEngineAPI",
        "{",
    ]
    first = True
    for title, functions in sections:
        if not first:
            out.append("")
        first = False
        if title:
            out.append(f"    // {title}")
        for ret, name, params in functions:
            args = ", ".join(f"{TYPES[t][0]} {n}" for t, n in params)
            out.append(f"    {TYPES[ret][0]} ( *{name} )( {args} );" if args else f"    {TYPES[ret][0]} ( *{name} )();")
    out += ["};", ""]
    return "\n".join(out)


def cs(sections):
    out = [
        "// Generated by Engine/Tools/GenerateScriptAPI.py from Engine/Source/Scripting/ScriptAPI.def - edit the manifest, not this file.",
        "using System.Runtime.InteropServices;",
        "",
        "namespace ScriptCore;",
        "",
        "[StructLayout(LayoutKind.Sequential)]",
        "public unsafe struct EngineAPIBindings",
        "{",
    ]
    first = True
    for title, functions in sections:
        if not first:
            out.append("")
        first = False
        if title:
            out.append(f"    // {title}")
        for ret, name, params in functions:
            types = [TYPES[t][1] for t, _ in params] + [TYPES[ret][1]]
            out.append(f"    public delegate* unmanaged<{', '.join(types)}> {name};")
    out += ["}", ""]
    return "\n".join(out)


def main():
    sections = parse()
    outputs = {CPP_OUT: cpp(sections), CS_OUT: cs(sections)}
    if "--check" in sys.argv:
        stale = []
        for path, text in outputs.items():
            try:
                with open(path, encoding="utf-8", newline="") as f:
                    current = f.read()
            except FileNotFoundError:
                current = None
            if current != text:
                stale.append(os.path.relpath(path, ENGINE))
        if stale:
            print("Script API out of date (run Engine/Tools/GenerateScriptAPI.py): " + ", ".join(stale))
            return 1
        print("Script API up to date")
        return 0
    for path, text in outputs.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote " + os.path.relpath(path, ENGINE))
    count = sum(len(functions) for _, functions in sections)
    print(f"{count} functions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
