name: macOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - macOS
        xcode:
          - ^12
        configuration:
          - Debug
          - Release
        type:
          - Editor
          - Game_macOS
    runs-on: macos-latest

    steps:
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile
        name: Grab the project setup file
        with:
          url: "https://raw.githubusercontent.com/wobbier/MitchEngine/${{github.ref_name}}/Tools/NewProjectSetup.command"
          target: ./

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"

      - name: Generate a new project
        shell: bash
        run: sh NewProjectSetup.command EmptyProject ${{github.ref_name}}

      - name: Generate a new project
        shell: bash
        run: cd Project && sh GenerateSolution.command && cd ../

      - name: Build Editor
        if: ${{ matrix.type == 'Editor' }}
        uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build # default = `test`
          code-coverage: true # default = `false`
          warnings-as-errors: false # default = `false`
          configuration: ${{ matrix.type }}_${{ matrix.configuration }} # no default, ie. `xcodebuild` decides itself
          scheme: Havana_mac

      - name: Build Game
        if: ${{ matrix.type == 'Game_macOS' }}
        uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build # default = `test`
          code-coverage: true # default = `false`
          warnings-as-errors: false # default = `false`
          configuration: ${{ matrix.type }}_${{ matrix.configuration }} # no default, ie. `xcodebuild` decides itself
          scheme: Game_EntryPoint_mac

      - name: Copy Assets (Not Implemented)
        shell: bash
        run: echo todo

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: EmptyProject - ${{matrix.type}} - ${{matrix.buildconfig}}
          path: |
            Build/${{matrix.buildconfig}}
